# Generated by Django 3.1.5 on 2021-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('paragraph', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
