# Generated by Django 3.1.5 on 2021-02-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmarket', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
